exec SelectAllBookings
exec SelectAllHosts
exec SelectAllListings


--1. List all listings along with their host name and whether the host is a superhost.
select  
    L.listing_id,
    L.listing_name,L.city,
    L.room_type,L.price_per_night,
    H.host_name, H.superhost 
from listings as L
left join hosts as H 
    on l.host_id=h.host_id ;

     
--2. Find the total number of listings in each city, sorted from highest to lowest.
select city, 
    count(listing_id) as Num_of_Listings from listings
group by city
order by Num_of_Listings desc


--3. Find the top 5 most booked listings based on number of bookings.
select top 5 
    l.listing_id, l.listing_name, 
    count(b.booking_id) as Total_booking
from bookings b
join listings l 
    on b.listing_id = l.listing_id
group by 
    l.listing_id, 
    l.listing_name
order by Total_booking desc


--4. Calculate the total revenue generated by each listing.

select 
    l.listing_id,
    l.listing_name,
    sum(b.total_price) as Total_Revenue
from bookings b
join listings l 
    on b.listing_id = l.listing_id
group by 
    l.listing_id, 
    l.listing_name
order by Total_Revenue desc

--5.For each city, rank listings by their price (highest price = rank 1).
select 
    city, 
    listing_name, 
    price_per_night,
    rank() over(partition by city order by price_per_night desc) as ranking 
from listings 


--6.Identify the top performing hosts based on total revenue generated from all their listings.
with host_revenue as (
    select 
        h.host_id,
        h.host_name,
        h.superhost,
        l.city,
        sum(b.total_price) as total_revenue
    from hosts as h
    join listings as l
        on h.host_id  = l.host_id
    join bookings b 
        on l.listing_id = b.listing_id
    group by
        h.host_id,
        h.host_name,
        h.superhost,
        l.city
)

select 
    host_id,
    host_name,
    superhost,
    city,
    Total_revenue,
    rank() over(order by Total_revenue desc) as global_Rank,
    rank() over(partition by city order by total_revenue desc) as city_Rank
from host_revenue
order by total_revenue desc


--7. Identify which listings have seasonal demand spikes by comparing their peak month bookings vs average monthly bookings.
with monthly_bookings as(
    select
        l.listing_id,
        l.listing_name,
        month(b.check_in) as booking_month,
        count(b.booking_id) as monthly_count
    from bookings b
    join listings l
        on b.listing_id = l.listing_id
    group by
        l.listing_id,
        l.listing_name,
        month(b.check_in)
),
 booking_stats as(
    select 
        listing_id,
        listing_name,
        avg(monthly_count) as avg_monthly_bookings,
        max(monthly_count) as peak_monthly_bookings
    from monthly_bookings
    group by 
        listing_id,
        listing_name
 )

 select
    listing_id,
    listing_name,
    avg_monthly_bookings,
    peak_monthly_bookings,
    (peak_monthly_bookings - avg_monthly_bookings) as spike_value,
    case
        when peak_monthly_bookings >= avg_monthly_bookings * 1.5
            then 'High Seasonality'
        when peak_monthly_bookings >= avg_monthly_bookings *1.2
            then 'Moderate Seasonality'
        else 'Low Seasonality'
    end as Seasonality_tag
from booking_stats
order by spike_value desc;
 

 --8.Identify the Top 3 hosts in each city based on: Revenue + Number of Bookings (Weighted Ranking).

 with top_hosts as(
    select 
        h.host_id,
        h.host_name,
        l.city,
        sum(b.total_price) as total_revenue,
        count(b.booking_id) as total_bookings
    from hosts h
    join listings l
        on h.host_id = l.host_id
    join bookings b
        on l.listing_id = b.listing_id
    group by
        h.host_id,
        h.host_name,
        l.city
),
ranked_host as (
    select
        host_id,
        host_name,
        city,
        total_bookings,
        total_revenue,
        dense_rank() over(partition by city order by total_revenue desc, total_bookings desc) as city_rank
    from top_hosts
)

select * from ranked_host
where city_rank <=3
order by city, city_rank 


--9.Find guests who booked more than once .
select
    b.listing_id,
    b.guest_name,
    l.city,
    count(b.booking_id) as Total_Bookings
from bookings b
join listings l
    on b.listing_id = l.listing_id
group by 
    b.listing_id,
    b.guest_name,
    l.city
having count(b.booking_id) > 1
order by Total_Bookings desc


--10.Calculate Occupancy Rate per Listing
select  
    l.listing_id,
    l.listing_name,
    sum(datediff(day, b.check_in , b.check_out)) as Total_nights_booked,
    cast(sum(datediff(day, b.check_in , b.check_out)) * 100 / 365 as decimal(10,2)) as occupency_rate_percentage
from listings l
left join bookings b
    on l.listing_id = b.listing_id
group by
    l.listing_id,
    l.listing_name
order by occupency_rate_percentage desc


--11.Identify Hosts Managing 2+ Listings
select 
    h.host_id,
    h.host_name,
    count(l.listing_id) as num_listings
from hosts h
join listings l
    on h.host_id = l.host_id
group by 
    h.host_id,
    h.host_name
having count(l.listing_id) >=2
order by num_listings


--12.Rank the most Popular Property Type per City
with type_count as(
    select 
        city,
        room_type,
        count(*) as total_listings,
        dense_rank() over(partition by city order by count(*) desc) as Rank
    from listings
    group by
        city,
        room_type
)
select 
    city,
    room_type,
    total_listings
from type_count
where Rank = 1;


--13.Find Listings With the Longest Average Stay Duration
select 
    l.listing_id,
    l.city,
    l.listing_name,
    avg(datediff(day, b.check_in, b.check_out)) as avg_stay_days
from listings l
join bookings b
    on l.listing_id = b.listing_id
group by
    l.listing_id,
    l.city,
    l.listing_name
order by avg_stay_days desc


--14.Revenue Contribution % by City
with city_rev as(
    select 
        city,
        sum(b.total_price) as city_revenue
    from listings l
    join bookings b
        on l.listing_id = b.listing_id
    group by city
),
 total_rev as (
    select
        sum(city_revenue) as total_revenue
    from city_rev
 )

select 
    c.city,
    c.city_revenue,
    cast(c.city_revenue * 100 / t.total_revenue as decimal(10,2)) as revenue_percentage
from city_rev c
cross join total_rev t
order by revenue_percentage desc


--15.Find Listings With No Bookings
select
    l.listing_id,
    l.listing_name,
    l.price_per_night
from listings l
left join bookings b
    on l.listing_id = b.listing_id
where b.booking_id is null


--16.Monthly Revenue Trend
select
    month(check_in) as Month,
    sum(total_price) as Monthly_revenue
from bookings 
group by month(check_in)
order by Monthly_revenue 


--17.City-Level Supply vs Demand Ratio
with supply as(
    select
        city,
        count(*) as total_listings
    from listings
    group by city
),

demand as(
    select
        l.city,
        count(b.booking_id) as total_bookings
    from bookings b
    join listings l
        on b.listing_id = l.listing_id
    group by l.city
 )

 select
    s.city,
    s.total_listings,
    d.total_bookings,
    cast(d.total_bookings *1.0 / nullif(s.total_listings,0) as decimal(10,2)) as Supply_Demand_ratio
from supply s
join demand d
    on s.city = d.city
order by Supply_Demand_ratio desc